import type { Context } from 'hono';
import * as si from 'simple-icons';
import { z } from 'zod';

import type { Component } from '~/libs/svg';

import { tag } from '../utils';

const createSimpleIcon =
  (
    d: string
  ): Component<{
    s?: string | number;
    c?: string;
  }> =>
  ({ s = 20, c = 'currentColor' }) => {
    return tag('svg', {
      role: 'img',
      viewBox: '0 0 24 24',
      width: s,
      height: s,
      fill: c,
      stroke: 'none',
      children: tag('path', { d }),
    });
  };

const SimpleIcons = {
  adonisjs: createSimpleIcon(si.siAdonisjs.path),
  algolia: createSimpleIcon(si.siAlgolia.path),
  'alpine.js': createSimpleIcon(si.siAlpinedotjs.path),
  angular: createSimpleIcon(si.siAngular.path),
  appwrite: createSimpleIcon(si.siAppwrite.path),
  arduino: createSimpleIcon(si.siArduino.path),
  assemblyscript: createSimpleIcon(si.siAssemblyscript.path),
  astro: createSimpleIcon(si.siAstro.path),
  atom: createSimpleIcon(si.siAtom.path),
  axios: createSimpleIcon(si.siAxios.path),
  behance: createSimpleIcon(si.siBehance.path),
  bento: createSimpleIcon(si.siBento.path),
  bitbucket: createSimpleIcon(si.siBitbucket.path),
  blender: createSimpleIcon(si.siBlender.path),
  bun: createSimpleIcon(si.siBun.path),
  capacitor: createSimpleIcon(si.siCapacitor.path),
  cloudflare: createSimpleIcon(si.siCloudflare.path),
  cloudflarepages: createSimpleIcon(si.siCloudflarepages.path),
  codeberg: createSimpleIcon(si.siCodeberg.path),
  codecov: createSimpleIcon(si.siCodecov.path),
  codeigniter: createSimpleIcon(si.siCodeigniter.path),
  codemirror: createSimpleIcon(si.siCodemirror.path),
  codepen: createSimpleIcon(si.siCodepen.path),
  codesandbox: createSimpleIcon(si.siCodesandbox.path),
  commitlint: createSimpleIcon(si.siCommitlint.path),
  css3: createSimpleIcon(si.siCss3.path),
  deno: createSimpleIcon(si.siDeno.path),
  'dev.to': createSimpleIcon(si.siDevdotto.path),
  discord: createSimpleIcon(si.siDiscord.path),
  docker: createSimpleIcon(si.siDocker.path),
  dribbble: createSimpleIcon(si.siDribbble.path),
  elasticsearch: createSimpleIcon(si.siElasticsearch.path),
  electron: createSimpleIcon(si.siElectron.path),
  esbuild: createSimpleIcon(si.siEsbuild.path),
  eslint: createSimpleIcon(si.siEslint.path),
  express: createSimpleIcon(si.siExpress.path),
  fastify: createSimpleIcon(si.siFastify.path),
  figma: createSimpleIcon(si.siFigma.path),
  firebase: createSimpleIcon(si.siFirebase.path),
  flutter: createSimpleIcon(si.siFlutter.path),
  git: createSimpleIcon(si.siGit.path),
  github: createSimpleIcon(si.siGithub.path),
  githubactions: createSimpleIcon(si.siGithubactions.path),
  githubpages: createSimpleIcon(si.siGithubpages.path),
  gitlab: createSimpleIcon(si.siGitlab.path),
  googlechrome: createSimpleIcon(si.siGooglechrome.path),
  graphql: createSimpleIcon(si.siGraphql.path),
  html5: createSimpleIcon(si.siHtml5.path),
  instagram: createSimpleIcon(si.siInstagram.path),
  javascript: createSimpleIcon(si.siJavascript.path),
  json: createSimpleIcon(si.siJson.path),
  keras: createSimpleIcon(si.siKeras.path),
  koyeb: createSimpleIcon(si.siKoyeb.path),
  kubernetes: createSimpleIcon(si.siKubernetes.path),
  laravel: createSimpleIcon(si.siLaravel.path),
  lerna: createSimpleIcon(si.siLerna.path),
  linkedin: createSimpleIcon(si.siLinkedin.path),
  mastodon: createSimpleIcon(si.siMastodon.path),
  medium: createSimpleIcon(si.siMedium.path),
  microsoftedge: createSimpleIcon(si.siMicrosoftedge.path),
  mongodb: createSimpleIcon(si.siMongodb.path),
  mysql: createSimpleIcon(si.siMysql.path),
  nativescript: createSimpleIcon(si.siNativescript.path),
  nestjs: createSimpleIcon(si.siNestjs.path),
  netlify: createSimpleIcon(si.siNetlify.path),
  'next.js': createSimpleIcon(si.siNextdotjs.path),
  nginx: createSimpleIcon(si.siNginx.path),
  'node.js': createSimpleIcon(si.siNodedotjs.path),
  notion: createSimpleIcon(si.siNotion.path),
  npm: createSimpleIcon(si.siNpm.path),
  'nuxt.js': createSimpleIcon(si.siNuxtdotjs.path),
  nx: createSimpleIcon(si.siNx.path),
  openai: createSimpleIcon(si.siOpenai.path),
  opencollective: createSimpleIcon(si.siOpencollective.path),
  payloadcms: createSimpleIcon(si.siPayloadcms.path),
  paypal: createSimpleIcon(si.siPaypal.path),
  penpot: createSimpleIcon(si.siPenpot.path),
  pexels: createSimpleIcon(si.siPexels.path),
  php: createSimpleIcon(si.siPhp.path),
  pinterest: createSimpleIcon(si.siPinterest.path),
  planetscale: createSimpleIcon(si.siPlanetscale.path),
  pnpm: createSimpleIcon(si.siPnpm.path),
  pocketbase: createSimpleIcon(si.siPocketbase.path),
  postgresql: createSimpleIcon(si.siPostgresql.path),
  preact: createSimpleIcon(si.siPreact.path),
  prettier: createSimpleIcon(si.siPrettier.path),
  prisma: createSimpleIcon(si.siPrisma.path),
  producthunt: createSimpleIcon(si.siProducthunt.path),
  pwa: createSimpleIcon(si.siPwa.path),
  python: createSimpleIcon(si.siPython.path),
  radixui: createSimpleIcon(si.siRadixui.path),
  react: createSimpleIcon(si.siReact.path),
  redis: createSimpleIcon(si.siRedis.path),
  redux: createSimpleIcon(si.siRedux.path),
  remix: createSimpleIcon(si.siRemix.path),
  render: createSimpleIcon(si.siRender.path),
  rust: createSimpleIcon(si.siRust.path),
  sanity: createSimpleIcon(si.siSanity.path),
  sass: createSimpleIcon(si.siSass.path),
  signal: createSimpleIcon(si.siSignal.path),
  simpleicons: createSimpleIcon(si.siSimpleicons.path),
  slack: createSimpleIcon(si.siSlack.path),
  solid: createSimpleIcon(si.siSolid.path),
  stackblitz: createSimpleIcon(si.siStackblitz.path),
  sublimetext: createSimpleIcon(si.siSublimetext.path),
  supabase: createSimpleIcon(si.siSupabase.path),
  svelte: createSimpleIcon(si.siSvelte.path),
  tailwindcss: createSimpleIcon(si.siTailwindcss.path),
  tauri: createSimpleIcon(si.siTauri.path),
  telegram: createSimpleIcon(si.siTelegram.path),
  tensorflow: createSimpleIcon(si.siTensorflow.path),
  threads: createSimpleIcon(si.siThreads.path),
  'three.js': createSimpleIcon(si.siThreedotjs.path),
  tiktok: createSimpleIcon(si.siTiktok.path),
  turborepo: createSimpleIcon(si.siTurborepo.path),
  typescript: createSimpleIcon(si.siTypescript.path),
  unocss: createSimpleIcon(si.siUnocss.path),
  unsplash: createSimpleIcon(si.siUnsplash.path),
  upstash: createSimpleIcon(si.siUpstash.path),
  vercel: createSimpleIcon(si.siVercel.path),
  visualstudiocode: createSimpleIcon(si.siVisualstudiocode.path),
  vite: createSimpleIcon(si.siVite.path),
  vitest: createSimpleIcon(si.siVitest.path),
  'vue.js': createSimpleIcon(si.siVuedotjs.path),
  webassembly: createSimpleIcon(si.siWebassembly.path),
  whatsapp: createSimpleIcon(si.siWhatsapp.path),
  windows: createSimpleIcon(si.siWindows.path),
  x: createSimpleIcon(si.siX.path),
  xampp: createSimpleIcon(si.siXampp.path),
  yarn: createSimpleIcon(si.siYarn.path),
  youtube: createSimpleIcon(si.siYoutube.path),
  zod: createSimpleIcon(si.siZod.path),
};

type SimpleIcon = keyof typeof SimpleIcons;

const SIMPLE_ICON = Object.keys(SimpleIcons) as unknown as [
  `adonisjs`,
  `algolia`,
  `alpine.js`,
  `angular`,
  `appwrite`,
  `arduino`,
  `assemblyscript`,
  `astro`,
  `atom`,
  `axios`,
  `behance`,
  `bento`,
  `bitbucket`,
  `blender`,
  `bun`,
  `capacitor`,
  `cloudflare`,
  `cloudflarepages`,
  `codeberg`,
  `codecov`,
  `codeigniter`,
  `codemirror`,
  `codepen`,
  `codesandbox`,
  `commitlint`,
  `css3`,
  `deno`,
  `dev.to`,
  `discord`,
  `docker`,
  `dribbble`,
  `elasticsearch`,
  `electron`,
  `esbuild`,
  `eslint`,
  `express`,
  `fastify`,
  `figma`,
  `firebase`,
  `flutter`,
  `git`,
  `github`,
  `githubactions`,
  `githubpages`,
  `gitlab`,
  `googlechrome`,
  `graphql`,
  `html5`,
  `instagram`,
  `javascript`,
  `json`,
  `keras`,
  `koyeb`,
  `kubernetes`,
  `laravel`,
  `lerna`,
  `linkedin`,
  `mastodon`,
  `medium`,
  `microsoftedge`,
  `mongodb`,
  `mysql`,
  `nativescript`,
  `nestjs`,
  `netlify`,
  `next.js`,
  `nginx`,
  `node.js`,
  `notion`,
  `npm`,
  `nuxt.js`,
  `nx`,
  `openai`,
  `opencollective`,
  `payloadcms`,
  `paypal`,
  `penpot`,
  `pexels`,
  `php`,
  `pinterest`,
  `planetscale`,
  `pnpm`,
  `pocketbase`,
  `postgresql`,
  `preact`,
  `prettier`,
  `prisma`,
  `producthunt`,
  `pwa`,
  `python`,
  `radixui`,
  `react`,
  `redis`,
  `redux`,
  `remix`,
  `render`,
  `rust`,
  `sanity`,
  `sass`,
  `signal`,
  `simpleicons`,
  `slack`,
  `solid`,
  `stackblitz`,
  `sublimetext`,
  `supabase`,
  `svelte`,
  `tailwindcss`,
  `tauri`,
  `telegram`,
  `tensorflow`,
  `threads`,
  `three.js`,
  `tiktok`,
  `turborepo`,
  `typescript`,
  `unocss`,
  `unsplash`,
  `upstash`,
  `vercel`,
  `visualstudiocode`,
  `vite`,
  `vitest`,
  `vue.js`,
  `webassembly`,
  `whatsapp`,
  `windows`,
  `x`,
  `xampp`,
  `yarn`,
  `youtube`,
  `zod`
];
const SIMPLE_ICON_DEFAULT = 'github' satisfies SimpleIcon;

const SimpleIconSchema = z.enum(SIMPLE_ICON, { required_error: 'Icon is required', invalid_type_error: 'Invalid icon' }).default(SIMPLE_ICON_DEFAULT);

const isSimpleIcon = (value?: unknown): value is SimpleIcon => SIMPLE_ICON.includes(String(value) as SimpleIcon);

const getValidSimpleIconQuery = async (context: Context, key: string = 'i') => await SimpleIconSchema.parseAsync(context.req.query(key));

export { SimpleIconSchema };
export { SimpleIcons };
export { isSimpleIcon };
export { getValidSimpleIconQuery };
