name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: write npmrc
        run: echo auto-install-peers=false >> .npmrc

      - name: run "pnpm install"
        run: pnpm install --no-frozen-lockfile

      - name: run "pnpm build"
        run: pnpm build

      - name: run "pnpm test"
        run: pnpm test

      - name: run "pnpm script:clean"
        run: pnpm script:clean

      - name: upload
        uses: denoland/deployctl@v1
        with:
          project: 'none'
          entrypoint: 'main.js'
          root: './dist'
