name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.11.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '1.38.3'

      - name: Write npmrc
        run: echo auto-install-peers=false >> .npmrc

      - name: Run "pnpm install"
        run: pnpm install

      - name: Run "pnpm build"
        run: pnpm build

      - name: Run "pnpm test"
        run: pnpm test

      - name: Run "pnpm script:clean"
        run: pnpm script:clean

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'none'
          entrypoint: 'main.js'
          root: './dist'
